### ISSUE TITLE
Generator failed to get element name inside TextBlock.Inlines

### ISSUE THREAD

**Issue by laolarou726** [AvaloniaUI/Avalonia.NameGenerator#105]
The generator failed to resolve any x:Name attribute in TextBlock.Inlines.

To repro:
```xaml

<TextBlock>
    <TextBlock.Inlines>
        <InlineCollection>
            <Run Text="Test" />
            <Run x:Name="NameText" Text="TEST1" />
        </InlineCollection>
    </TextBlock.Inlines>
</TextBlock>

```

It can not generate a reference for element `NameText`

**Comment by worldbeater** [comment]
The fix is now :ship: to NuGet as [version 1.6.1](https://www.nuget.org/packages/XamlNameReferenceGenerator/1.6.1).
This bug existed due to the following line: https://github.com/AvaloniaUI/Avalonia.NameGenerator/blob/da39281ecf47bc50b8f0a1db01327a8a25f8602e/src/Avalonia.NameGenerator/Generator/ResolverExtensions.cs#L8 We were checking if a named control is `IControl`, but the new inline `Run` element is not an `IControl`. According to https://github.com/AvaloniaUI/Avalonia/blob/87e7f46a97dcc67d701edd483ebdb47dd6c69e7c/src/Avalonia.Base/StyledElement.cs#L54 any `StyledElement` can be named, so changing the old check to the following helped: 
https://github.com/AvaloniaUI/Avalonia.NameGenerator/blob/59056ab95a18c77caf5dda3000e982e7a869870f/src/Avalonia.NameGenerator/Generator/ResolverExtensions.cs#L8
