### ISSUE TITLE
Is the x:FieldModifier Directive supported?

### ISSUE THREAD

**Issue by robloo** [AvaloniaUI/Avalonia.NameGenerator#19]
This is needed to change name fields to public/protected instead of private. Especially necessary for derived controls in certain situations.

https://docs.microsoft.com/en-us/dotnet/desktop/xaml-services/xfieldmodifier-directive

**Comment by maxkatz6** [comment]
Right now all properties are internal.

**Comment by robloo** [comment]
Yea, I noticed that after checking the example. This still applies though. There are some cases where public might be needed (although I cant think of anything that isn't a contrived example) and other cases where protected is better so it is visible only to derived controls instead of the whole namespace.

**Comment by worldbeater** [comment]
I guess in order to implement this, we should add an extra check somewhere here https://github.com/AvaloniaUI/Avalonia.NameGenerator/blob/main/src/Avalonia.NameGenerator/Infrastructure/NameReceiver.cs#L39 right before adding the observed `(string TypeName, string Name)` pair to the list of the named controls. E.g. probably worth changing the type to `(string TypeName, string Name, string? FieldModifier)` and then modify the generator itself https://github.com/AvaloniaUI/Avalonia.NameGenerator/blob/main/src/Avalonia.NameGenerator/NameReferenceGenerator.cs#L112 (and do somewhat like `"{info.FieldModifier ?? "internal"}" ...` there). Please feel free to open a PR that implements this.

**Comment by worldbeater** [comment]
`x:FieldModifier` support is shipped 🚢

The minimum requirements are:
- `XamlNameReferenceGenerator ^0.1.10`
- `Avalonia ^0.10.999-cibuild0012810-beta`

**Comment by robloo** [comment]
Awesome work! This will be a big help for those that need it!
